### ISSUE TITLE
Failed on `gpu-api=d3d11`

### ISSUE THREAD

**Issue by dyphire** [natural-harmonia-gropius/hdr-toys#1]
the log file: [mpv.log](https://github.com/natural-harmonia-gropius/hdr-toys/files/10707480/mpv.log)

**Comment by natural-harmonia-gropius** [comment]
修好了，commit rebase掉了

**Comment by dyphire** [comment]
测试了下虽然d3d11下可以使用了，但是gpu占用直接吃满，vulkan下只有30%左右的占用。性能差距过大

**Comment by natural-harmonia-gropius** [comment]
那个占用率算法有问题感觉，建议用hwinfo看实时功耗来评估负载，我这边d3d11和vk功耗一致

**Comment by dyphire** [comment]
> 那个占用率算法有问题感觉，建议用hwinfo看实时功耗来评估负载，我这边d3d11和vk功耗一致

直接看的任务管理里的GPU占用

**Comment by natural-harmonia-gropius** [comment]
那个……至少在我看来……很不准……
频率很低的时候它就高，频率高了它就低
我这边总是d3d11占用高但是频率低，vk反过来
