### ISSUE TITLE
[bug] 黑暗场景的严重性错误

### ISSUE THREAD

**Issue by dyphire** [natural-harmonia-gropius/hdr-toys#12]
目前的shader动态映射方案在明亮场景测试下表现良好，但在某些黑暗场景下发现了严重性错误
测试视频：[subbers]Violet Evergarden the Movie [UHDRip HEVC-yuv420p10 Dolby-Vision FLAC ASSx2 PGS].mkv
| bt.2446a | dynamic |
| -------- | ------- |
| ![image](https://user-images.githubusercontent.com/61936050/220047942-be54fc90-454e-49d6-b71b-29d2d4f9a03d.png)   | ![image](https://user-images.githubusercontent.com/61936050/220047992-88a26761-acaf-4fd2-972e-77dcfd47b669.png)    |

该测试场景下shader动态映射的画面全黑。由于测试视频是之前剪切的，时间只是确定为章节 ギルベルトの行方 的2分52秒

**Comment by natural-harmonia-gropius** [comment]
fixed by https://github.com/natural-harmonia-gropius/hdr-toys/commit/1dfe4a929e5004a0ab35ec3d2a0bafa4f1f8e49a
