### ISSUE TITLE
Question on HDR->SDR for Projector users

### ISSUE THREAD

**Issue by danbezerra** [natural-harmonia-gropius/hdr-toys#14]
Interesting approach. I am a MadVR user but looking for an alternative given the unclear path forward with MadVR. On my scenario, I want to tone map HDR to SDR, but keeping BT.2020 as the color space. I also want to take advantage of my projector max nits, which is about 100 nits. That's basically what I do with MadVR v166 today.

What modifications do I need to make to get there?

Thanks

**Comment by natural-harmonia-gropius** [comment]
> keeping BT.2020 as the color space.

remove `glsl-shader=~~/shaders/hdr-toys/gamut-mapping/compress.glsl`

> take advantage of my projector max nits, which is about 100 nits.

add `glsl-shader-opts-add=L_sdr=100`

**Comment by danbezerra** [comment]
Thanks! Yes, Display Peak Luminance is the max nits you can get out of your projector. So in my case, 100 nits. I will give it a try and report back what I find!

**Comment by danbezerra** [comment]
Ok, I did a few initial tests - using my monitor, not the projector yet. Because of that, I kept the compress.glsl line since my projector doesn't support BT.2020.

Overall I like the results. However, when I stressed it using a few clips that are part of my MadVR stress test, I found that the results were not quite at MadVR level yet. See the attached screenshots.

MPV - Scene from Dawn of the dead.
![mpv](https://user-images.githubusercontent.com/17623925/223262247-4da6808a-3f7d-475b-afb4-387b74a8c4d7.png)

MadVR - same scene. Notice how you have more details in the big explosion.
![madvr](https://user-images.githubusercontent.com/17623925/223263304-cf224fd5-6e70-4991-a660-c34cbd856478.jpg)

Batman Vs Superman - difference is even higher
MPV:
![mpv2](https://user-images.githubusercontent.com/17623925/223264033-d6469eb9-c697-4809-b420-fc85ff387922.png)

MadVR:
![madvr2](https://user-images.githubusercontent.com/17623925/223264200-de4caeba-ba4e-4c94-81ed-826387d2a5e5.png)

Both MPV and MadVR are configured with 100 nits max, BT.709.

**Comment by natural-harmonia-gropius** [comment]
Can you share those clips?
`ffmpeg -i input.mp4 -ss 00:00 -t 10 output.mp4`

**Comment by danbezerra** [comment]
Here you are:
https://mega.nz/file/eSQXgYCB#4QP_1TK-DXNdaxawVtrs4duLpiQ5VGNAEuFxqgRrWj0
https://mega.nz/file/oyYEka6B#UriHFxFX0CyQM2YM_9izjOFRMs-bMjR9sZ1E8mqQgW4

**Comment by natural-harmonia-gropius** [comment]
With the curves I'm using now, those scenes are impossible to have a good look as madVR.🥲
This definitely requires a histogram-based curve.

This is the ideal image, result of clip and -5 stops exposure value with L_sdr=100.
![image](https://user-images.githubusercontent.com/50797982/223515798-6033083e-ca3b-4b1c-88f3-f5be4703fa8f.png)

**Comment by danbezerra** [comment]
Understood. Thanks for checking! Overall, I like the results of your model. Do you know if a histogram-based curve is planned for MPV?
