### ISSUE TITLE
MadVR settings used in your comparison

### ISSUE THREAD

**Issue by danbezerra** [natural-harmonia-gropius/hdr-toys#17]
First, thanks for the transparency by showing which settings were used in the comparison with MadVR. However, there are a few MadVR tweaks that you should consider when doing the comparison - for example, you are not using the recent TM curves nor the roll-off clipped pixel settings - both considered important improvements added to the most recent versions of MadVR. Here is my suggestion - in case you want to do a new round of comparisons:

1. Baseline settings (settings recommended by Javs, one of the most active contributors in the AVS thread)
![image](https://user-images.githubusercontent.com/17623925/226145284-07f652cf-2408-4677-9622-01e220713dac.png)

2. Potential tweaks over the base settings above:
- Use a more punchy curve - Mercury, and increase the punch a bit (I would not go above 7)
- uncheck the apply-desat 2-4 option (I don't see the need with the new builds/roll-off option enabled)
-  Use Lum Method - Sep (some folks get a more "punchy" image with Sep) and disable HTSM: No brightening.
- Enable Dynamic Clipping with a value of around 75-100.

Curious to see the results on your side.

**Comment by natural-harmonia-gropius** [comment]
I will redo the comparisons when I have time to.

**Comment by natural-harmonia-gropius** [comment]
I haven't used madVR for a long time, I have some questions.

1. There will be some artifacts that look like this. How to fix?
   ![image](https://user-images.githubusercontent.com/50797982/226176010-7967adbf-12ab-4d10-958a-0a9af56bbc44.png)
   I have enabled these options.
   ![image](https://user-images.githubusercontent.com/50797982/226176319-15c30113-81e9-4a27-80c4-051d2a4a6c75.png)
2. HLG seems been directly outputed. How to make it works with tone-mapping?
3. These two selects are disabled, is this normal?
   ![image](https://user-images.githubusercontent.com/50797982/226176519-baac58a3-62ef-4180-a22a-73fe2ab426c5.png)

**Comment by danbezerra** [comment]
1) I have not seen that on my side. I also don't use any artifact removal  or image enhancement options. Not sure what could trigger that - how is your scaling options?
2) HLG - I don't think MadVr offers any support for HLG. I don't use it personally, but I looked around the AVSForum thread and one user suggested to force PQ when feeding MadVR with HLG as a workaround. Not sure if it would work as I never tried it.
3) Disabled Settings - That's because you have a few HDR items selected in the "Trade Quality for Performance" tab. Uncheck all HDR related items and you will see that those options will become available. 
4) Peak Nits should be your display Max nits (mine is around 100 - JVC projector). Other than that your settings look good to me  - you can always play with the lum methods as I pointed out before.

**Comment by nicko88** [comment]
- You should not need artifact removal or image enhancement options normally.  Your artifact is strange, but I think there must be another reason for it.  Perhaps the trade quality for performance options.  So I agree all those need to be unchecked.  If you can upload a clip we can check for that artifact in our setups as I do not think it would be present in my madVR setup.
- madVR as far as I know doesn't work with HLG.
- For comparison, I think I would go with peak nits 100.  This seems to be the standard that people testing and developing madVR use.  Also as HDR tone-mapping is most used by projector users, rarely does someone have over 100 nits and often they have less.  For example I have 75 nits with my JVC projector.
- The settings in the first post are probably best to use.  Not my personal favorite, but seems to be the most "accurate" when comparing to a reference HDR display, and many on the madVR testing side agree and like those settings.

**Comment by natural-harmonia-gropius** [comment]
> Your artifact is strange

The artifact seems to be an issue of DXVA2, I switched to D3D11 in LAV and it disappeared.

> You should not need artifact removal or image enhancement options

I unchecked all of trade quality and artifact removal.
About the scaling: ngu-aa for chroma, ssim for down, ngu-sharp for up.

> madVR as far as I know doesn't work with HLG.

That sounds sad.

> The settings in the first post

max3 54 doesn't exist in 166 anymore, which one should I use? sep?

Current settings:
![image](https://user-images.githubusercontent.com/50797982/226416798-b52a77f2-4f32-4362-ae36-65124e0b1561.png)

**Comment by nicko88** [comment]
Ah yeah, 

> The artifact seems to be an issue of DXVA2, I switched to D3D11 in LAV and it disappeared.

Good call.  DXVA2 is old and IMO should be avoided.  DXVA2 Native was not a lossless decode, DXVA2 (Copy-back) is, but D3D11 is just better all around.  

> About the scaling: ngu-aa for chroma, ssim for down, ngu-sharp for up.

This is fine, but I am not sure why anyone ever decided NGU-AA was best for chroma.  All the evidence i've seen show that NGU-Sharp is just always best and even NGU-Sharp Low beats NGU-AA Very High.  But this is scaling and not really relevant to tone-mapping anyways.

> max3 54 doesn't exist in 166 anymore, which one should I use? sep?

max3 is the new name for max3 54.  max3 variant 1 and variant 2 are new minor tweaks to max3 and it seems that 1 of these 3 will be chosen going forward but we don't know which yet.  Either way, max3 seems to be the front-runner for the lum method that most people seem to prefer, and it creates the most subjectively close image to a reference grading display.

sep is very old, but it sounds like it will be sticking around as another option.  Personally I prefer sep, but it's clearly less "artistic intent" than max3.  the madVR developer wants those of us who like sep to start testing custom sep, so probably that is the one that will stick around going forward.

These are the last settings that I've seen posted that were for the most part front running.

https://www.avsforum.com/cdn-cgi/image/format=auto,onerror=redirect,width=1920,height=1920,fit=scale-down/https://www.avsforum.com/attachments/1675808073580-png.3400447/

So I would match that as closely as possible, choosing one of the 3 new max3 settings.

For your current settings I think the main thing would be to disable dynamic clipping.

Mercury punch 6 is good though IMO.  It's got a bit more punch than Saturn.

**Comment by natural-harmonia-gropius** [comment]
> 2 things I'd like to have clarified for the next build:
> 
> 1) Are we all good with gamut-rolloff 75-18? If so, I'll lock that in and remove the value options in the next build (but a disable/enable option will remain for now).
> 
> 2) Fer15 suggests that "max3 variant 2" is ever so slightly superior to the other 2 variants. He's suggesting using a mix of 65 with 90 red and 60 blue, with a highlight sat of 5. Are there any objections to this? Otherwise I'll lock that in for the next build and remove the other two max3 variants.

I will wait for the next build.

Current settings:
![image](https://user-images.githubusercontent.com/50797982/226506575-9edeae7e-9a08-4dd6-a479-599b84a4b752.png)

**Comment by kasper93** [comment]
One things to be careful of, "dynamic target nits" will adjust your DPL, quite aggressively. For comparison you probably want to avoid using it. "Highlight sat" also is little bit high. And "apply desat 2-4" is also not that commonly recommended.

But to really understand what's going on you would need to skim https://www.avsforum.com/threads/improving-madvr-hdr-to-sdr-mapping-for-projector-no-support-questions.2954506 thread, but there is not much update there recently.

Anyway except the lum method and TM curve, rest is sprinkles on top and doesn't matter that much, if someone wants to compare specific settings, well DIY.

**Comment by kasper93** [comment]
> But if you turn off DTN then you entirely disable dynamic tone-mapping and set madVR back to the stone ages in terms of modern tone-mapping techniques.

No, that's not correct. DTN is not related to DTM (dynamic tone mapping) as a whole. madVR always measures the frame and applies dynamic tone mapping, based on the current frame measured nits and so on.

DTN is essentially boosting the target nits parameter (of your display) which essentially darkens the image. I'm arguing here it is not something you want to do, especially if you want to compare tone mapping result. You know tone mapping to 203 nits is harder than tone mapping to 700 nits and darkening the output is cheap trick to make it look better, but in the same time too dark.

**Comment by nicko88** [comment]
I've never been able to get a good tone-mapping result without using DTN.  madshi says using DTN is absolutely the way to go when watching content.

If I don't use DTN then some scenes either look too bright and washed out / flat, or some scenes look too dark and hard to see the details.

I guess I don't know anyone using madVR that isn't using DTN, so I am not sure what is the value of making a comparison with it off.

**Comment by danbezerra** [comment]
I agree we need to do the comparison with the best known MadVR settings, which includes DTN. This is how we will measure the gap between MadVR and HDRToys and identify improvements for the future.

**Comment by kasper93** [comment]
> > Which scenes look too dark?
> 
> Some examples: Game of Thrones - S08E03 House of the Dragon - S01E07 The Book of Boba Fett - S01E01

I ask, because I don't believe DTN has ability to brighten the image. It has ability to rise the "internal DPL", which in turn will always produce darker output image.

> You call it a limitation, but so far no other tone-mapping system for me comes close to the pleasing image I can get with madVR and it's exactly because of things like DTN and others.

Sure, and with very low DPL, it can be a problem. Where DTN silently fixes for you, by making everything darker for scenes with higher dynamic range.

Anyway this discussion is pointless, I don't want to argue about the madVR superiority or not. It is just that comparing scenes with different DPL between software will produce different brightness above anything else. But like I said, it is a valid comparison and in the same time you should always compare it on your viewing setup (and your settings), because screenshots will not always show the true output as you would see it.

**Comment by nicko88** [comment]
Right it doesn't brighten.  I brighten by lowering DPL, but with a combination of NCL (no compression limit) and DTN, I am able to prevent brighter scenes from otherwise blowing out and being too bright and flat.

Maybe just include a shot from madVR with DTN on and off to cover all bases.  I would love other tone-mapping softwares to have options like DTN or similar.  I want more knobs so that I can dial things in the way I think they look best on my particular setup.

To me that is the strength of madVR (it's customizability) and what I feel I am lacking in other softwares thus preventing me from achieving my ideal desired result and then ultimately not using them because of that.

**Comment by natural-harmonia-gropius** [comment]
I decided to remove the Comparisons.md, which is moot and hard to maintain.
