### ISSUE TITLE
A shader that perceptually adds bloom to visually make highlights brighter

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [natural-harmonia-gropius/hdr-toys#19]
Hi, really nice shaders. I think it could be great to have a shader that would add some perceptual bloom to some bright parts of the image to visually make them brighter. I am not sure what should the parameters and the PSF be, however.

**Comment by natural-harmonia-gropius** [comment]
Bloom effect should be produced by the video itself. As an alternative, [Abney effect](https://en.wikipedia.org/wiki/Abney_effect) already exists in `chroma_correction` and `dynamic`.

**Comment by natural-harmonia-gropius** [comment]
I did a quick test, are you happy with the result? (ignore obvious artifacts)

![image](https://user-images.githubusercontent.com/50797982/227712225-04db7a28-2250-4a27-9294-3802a5b32b95.png)

![image](https://user-images.githubusercontent.com/50797982/227712262-0091341c-9078-4fd0-82c1-025524e5cf3f.png)

**Comment by natural-harmonia-gropius** [comment]
https://youtu.be/nh3gqtbYRkM?t=115
The result of a real pro-mist filter can be this. as you said, it looks dreamy.

**Comment by natural-harmonia-gropius** [comment]
Honestly it's beyond my capabilities. Things are far more complicated than thought, I think this requires AI analysis and PBR simulation, since the luminance of videos is not the real physical luminance.

So, I close this issue.
