### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by danbezerra** [natural-harmonia-gropius/hdr-toys#20]
Last night while watching Godzilla with my kids I noticed quite a bit of flickering. I'm using the latest HDR-Toys shaders, skipping the compress step (to keep SDR.BT2020). My SDR peak is set to 100 nits.

Here is a sample- let me know if you see the same flickering. Any changes I can make on my side to fix this?

https://mega.nz/file/zfJWhDrQ#88RTG179k1c5ozh2iY4e7tYWqDYKfnmKgko6MttHv2Y

**Comment by natural-harmonia-gropius** [comment]
Good sample, but can't solve it now.

Keep this issue open until the sample works well.

> Any changes I can make on my side to fix this?

Use madVR.

**Comment by pbiancardi** [comment]
> Good sample, but can't solve it now.
> 
> Keep this issue open until the sample works well.
> 
> > Any changes I can make on my side to fix this?
> 
> Use madVR.

Just curious if any work has been done on this or is planned?

**Comment by natural-harmonia-gropius** [comment]
> any work has been done on this or is planned?

https://github.com/natural-harmonia-gropius/mpv-config/pull/21
But I think I need to wait for https://github.com/haasn/libplacebo/issues/152 be done before this.

Or anybody can provide better filter function than the harmonic mean for temporal data?

---

Also, is this problem widespread? Most of my samples here are kind of Vlog rather than film.

**Comment by pbiancardi** [comment]
> > any work has been done on this or is planned?
> 
> [natural-harmonia-gropius/mpv-config#21](https://github.com/natural-harmonia-gropius/mpv-config/pull/21) But I think I need to wait for [haasn/libplacebo#152](https://github.com/haasn/libplacebo/issues/152) be done before this.
> 
> Or anybody can provide better filter function than the harmonic mean for temporal data?
> 
> Also, is this problem widespread? Most of my samples here are kind of Vlog rather than film, they rarely have noticeable flickering.

I am going to watch some films and see what I think.  I have been using MadVR Envy for last year or so but sold so now on MPV.  I have been using spline which seems really good but I want to try HDR Toys.  I will report back on how noticeable I think it is.

**Comment by natural-harmonia-gropius** [comment]
Please continue this issue in https://github.com/natural-harmonia-gropius/hdr-toys/issues/28.
