### ISSUE TITLE
Changes in brightness up and down

### ISSUE THREAD

**Issue by ANONIMNIQ** [natural-harmonia-gropius/hdr-toys#21]
I'm not sure why this happened, but when I watch some movies like The Martian I noticed that during the same scene brightness changed several times. Any setting to fix this?

**Comment by natural-harmonia-gropius** [comment]
Not currently, Could be part of https://github.com/natural-harmonia-gropius/hdr-toys/issues/5.
I think I should to use 99.7% peak instead of 100% peak (currently using) to fix this.

**Comment by ANONIMNIQ** [comment]
> Not currently, Could be part of #5. I think I should to use 99.7% peak instead of 100% peak (currently using) to fix this.

Do you plan to make some test version with this change? I'll like to test it.

**Comment by danbezerra** [comment]
similar to issue #20

**Comment by natural-harmonia-gropius** [comment]
Please continue this issue in https://github.com/natural-harmonia-gropius/hdr-toys/issues/28.
