### ISSUE TITLE
Libplacebo errors when using other operators than dynamic

### ISSUE THREAD

**Issue by aboulfad** [natural-harmonia-gropius/hdr-toys#22]
Hello,

If I set glsl-shader=~/shaders/hdr-toys/tone-mapping/dynamic.glsl to bt2390 for [bt.2100-pq] I get bunch of errors in the console. Other operators seem to yield errors too. 

Attached an error log file, and the mpv config file with renamed extension to .txt so it can be uploaded here.

mpv version: 0.35.1
libplacebo version: v5.264.0

[hdr-toys-bt2390-errors.log](https://github.com/natural-harmonia-gropius/hdr-toys/files/11300001/hdr-toys-bt2390-errors.log)
[mpv.txt](https://github.com/natural-harmonia-gropius/hdr-toys/files/11300010/mpv.txt)

Thank you.

**Comment by natural-harmonia-gropius** [comment]
> Other operators

Does reinhard works?

> [vo/gpu-next] opengl cocoa backend is deprecated, use vo=libmpv instead

I don't know about how mpv works on macos, try `gpu-api=vulkan` (If it works).

> VO: [gpu-next] 4096x2160 videotoolbox[p010]

Try hwdec=auto-safe (Although I don't think it has anything to do with it).

**Comment by aboulfad** [comment]
> Does reinhard works?
> 
Sadly no, similar errors, here's the first few lines:
`[vo/gpu-next/libplacebo] shader compile log (status=0): ERROR: 0:73: Initializer not allowed
[vo/gpu-next/libplacebo] ERROR: 0:74: Initializer not allowed`
> > [vo/gpu-next] opengl cocoa backend is deprecated, use vo=libmpv instead
> 
> I don't know about how mpv works on macos, try `gpu-api=vulkan` (If it works).
> 
In general, mpv/macOS works ok with vo=gpu (but not great for HDR movies on SDR monitors), its only with gpu-next which uses "apparently" the deprecated cocoa backed that may have issues. Only gpu-api=opengl works.
> > VO: [gpu-next] 4096x2160 videotoolbox[p010]
> 
> Try `hwdec=auto-safe` (Although I don't think it has anything to do with it).

It falls back to using hardware decoding (videotoolbox) and still errors.

I guess maybe open another issue in libplacebo ?

**Comment by natural-harmonia-gropius** [comment]
> maybe open another issue in libplacebo ?

Yes, I think.
