### ISSUE TITLE
HDR Toys washed out vs Spline

### ISSUE THREAD

**Issue by pbiancardi** [natural-harmonia-gropius/hdr-toys#30]
Figured I would open a new issue for this.

HDR Toys seems very washed out to me, almost like a gamma or level issue somewhere.  It is very visible with the debug menu even (top Spline bottom HDR Toys).

<img width="960" alt="Spline" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/9c43ca81-75ae-4b57-aed3-1b85417553e8">

<img width="960" alt="HTOY" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/73542fb8-4e6e-45c5-808c-a1660a266fd2">
 this

**Comment by natural-harmonia-gropius** [comment]
Grayed subtitles and osd are expected, they followed target-*.

Try to replace `calc_user_params_from_metered()` in dynamic.glsl and modify the value of `shadow`.
```glsl
void calc_user_params_from_metered() {
    float L_min_ev = log2(L_min / L_sdr);
    float L_max_ev = log2(L_max / L_sdr);
    float L_hdr_ev = log2(L_hdr / L_sdr);

    float shadow = 1.0;
    shoulderLength = L_max_ev / L_hdr_ev;
    shoulderStrength = L_max_ev;
    toeLength = shadow * L_max_ev / CONTRAST_sdr;
    toeStrength = 0.5 + 0.5 * (shadow * L_min / toeLength);
}

```

**Comment by pbiancardi** [comment]
Is   float shadow = 16.0 too high?  Somewhere in there looks better to me.  Also you don't seem to have the red push that is happning in spline right now?  HDR Toys 16.0 first spline second.

<img width="960" alt="HDR Toys 159732" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/9a66fe1b-075a-400a-965f-816424844d50">

<img width="960" alt="Spline 159732" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/d50a6e78-feea-445e-aa0b-2bf4e7966175">

**Comment by pbiancardi** [comment]
HDR Toys 16 first Spline second, with this adjustment I am not washed out anymore and I get rid of that red push (I assume that should not be near as red as spline makes it).
<img width="960" alt="HDR Toys 181109 16 shadow" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/905b4261-cd69-4db2-80d6-d51de8a170ab">

<img width="960" alt="Spline 181109" src="https://github.com/natural-harmonia-gropius/hdr-toys/assets/133981792/be549d0c-2d32-4b9a-b017-3c515eb17d00">

**Comment by pbiancardi** [comment]
NM when watching this very noticeably flickers with higher values.

**Comment by natural-harmonia-gropius** [comment]
`ffmpeg -i input.mp4 -ss 00:00 -t 10 output.mp4`
Take some clips plz.

**Comment by pbiancardi** [comment]
> ```glsl
> void calc_user_params_from_metered() {
>     float L_min_ev = log2(L_min / L_sdr);
>     float L_max_ev = log2(L_max / L_sdr);
>     float L_hdr_ev = log2(L_hdr / L_sdr);
> 
>     float shadow = 1.0;
>     shoulderLength = L_max_ev / L_hdr_ev;
>     shoulderStrength = L_max_ev;
>     toeLength = shadow * L_max_ev / CONTRAST_sdr;
>     toeStrength = 0.5 + 0.5 * (shadow * L_min / toeLength);
> }
> ```

Here you go, this one is really bad right when the guy at the bar turns around.  There is no flicker with MadVR or Spline.  There is a little flicker with your current master code.  There is a little flicker with the code posted here and it gets worse the higher I put float shadow.  

https://www.dropbox.com/s/71203a4uvy3j7j0/Creed.mkv?dl=0

**Comment by natural-harmonia-gropius** [comment]
Can you try https://github.com/natural-harmonia-gropius/hdr-toys/pull/31?

And could you take a clip of the https://github.com/natural-harmonia-gropius/hdr-toys/issues/30#issuecomment-1606153789?

**Comment by pbiancardi** [comment]
> Can you try #31?
> 
> And could you take a clip of the [#30 (comment)](https://github.com/natural-harmonia-gropius/hdr-toys/issues/30#issuecomment-1606153789)?

This is looking really good.

Here is the clip - https://www.dropbox.com/s/psq24onerdyymoj/output.mkv?dl=0
