### ISSUE TITLE
picture is over exposed and realy white

### ISSUE THREAD

**Issue by ofirielon** [natural-harmonia-gropius/hdr-toys#33]
as the title says.
added a picture.
![Screenshot 2023-07-11 211835](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/8cb1da1d-f6c3-41dc-b8bc-52102eae5902)

**Comment by natural-harmonia-gropius** [comment]
Any error in console? and take a screenshot of the frame timing page of stats please.

![image](https://github.com/natural-harmonia-gropius/hdr-toys/assets/50797982/90e1baea-2774-44d1-bfbf-c6500e19fd43)

**Comment by ofirielon** [comment]
i did copied the code with no changes i have attached the relevent photos as requested
![1](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/e1ecabce-27eb-4794-90de-0e61cd6cf81b)
![2](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/da9ba4f5-f62a-4d97-8f5d-6e7818b708f4)

**Comment by natural-harmonia-gropius** [comment]
Add `vo=gpu-next` to your mpv.conf, above the profiles

```
vo=gpu-next

[xxxxx]
...
````

**Comment by ofirielon** [comment]
ty for the respond.i know see you wrote that libplacebo is required but no documentation on how to use it on windows.sadly the problem was me and i gues i have to give up on your creation,sadly.thank you very much for the help.i hope windows guide wil be made one day

**Comment by natural-harmonia-gropius** [comment]
libplacebo has been included in this -> https://github.com/shinchiro/mpv-winbuild-cmake/releases

You just need to update your mpv.exe and add vo=gpu-next.

**Comment by ofirielon** [comment]
did as you said and got bit fruther now i only get those eror of unrecognised commands
![3](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/f3cc4785-163c-4272-8000-3f4b6b527efd)

**Comment by natural-harmonia-gropius** [comment]
add vo=gpu-next to your mpv.conf

**Comment by natural-harmonia-gropius** [comment]
Did you donload mpv from https://github.com/shinchiro/mpv-winbuild-cmake/releases?
