### ISSUE TITLE
doesnt work wih mpv.net

### ISSUE THREAD

**Issue by ofirielon** [natural-harmonia-gropius/hdr-toys#35]
litterly not working whan using mpv.net,with what gui it works?

**Comment by natural-harmonia-gropius** [comment]
Download "mpv-dev" in https://github.com/shinchiro/mpv-winbuild-cmake/releases
Extract it, rename "libmpv-2.dll" to "mpv-2.dll".
Replace "mpv-2.dll" in mpv.net folder.

Other gui can get work in same way.

**Comment by ofirielon** [comment]
ty for responding.its aint helping so i just gave up and use mpv itself.you wrote some amazing software here ty!
