### ISSUE TITLE
found a color bug

### ISSUE THREAD

**Issue by ofirielon** [natural-harmonia-gropius/hdr-toys#41]
yellow and red highlights turned to white color il add some photos.
![redyellow1](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/b7887974-7ab8-4870-99ef-704bf460459f)
![redyellow2](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/49dc288c-2fa2-42b8-aecc-8b0c19ec8553)
![yellow1](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/3898d3e0-9b5d-4178-b92d-62d211fc4fea)
![yellow2](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/0b4a1a94-7693-43e8-b376-2687770850b0)
![blue1](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/89d4859c-4f02-4bd5-ba32-3d2cbb008246)
![blue2](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/81a1f16b-b848-454f-b77e-6a68ddb4df21)
 this is the link to the video-https://www.youtube.com/watch?v=8MCFqGnYW4M

**Comment by natural-harmonia-gropius** [comment]
Try to remove the utils/chroma_correction.glsl and change gamut-mapping/jedypod.glsl to gamut-mapping/clip.glsl

**Comment by ofirielon** [comment]
ty for responding.have tried,no change.it still happens on red and yellow.

**Comment by natural-harmonia-gropius** [comment]
The tower is a bit orange, you can recheck this by using bt2390 or bt2446c. madvr shows orange too. "paris" and "planet" is too bright, and "ph" too colorful. so, they got pretty highly desaturation.

youtube's conversation make some blue turns purple, It can't be reference.

**Comment by ofirielon** [comment]
i have attached photos.red and yellow crushed to white on hdr toys as you can see.
![mpv](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/fd268e44-091e-4811-a0e8-5bbf1c267ef6)
![madvr](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/0c310a3e-a1c6-4420-afa1-ffee5d2920f3)

**Comment by natural-harmonia-gropius** [comment]
Whole image of your madvr screenshot not red enough, blue not good too.

This is most ref image I think.

![image](https://github.com/natural-harmonia-gropius/hdr-toys/assets/50797982/87e1a7be-0e88-4b7a-8099-7e9ab3044410)

![image](https://github.com/natural-harmonia-gropius/hdr-toys/assets/50797982/73f2bc14-0600-4680-a539-41597f3e7d00)

**Comment by natural-harmonia-gropius** [comment]
But yes, yellow needs some tweaking.

**Comment by ofirielon** [comment]
thanks for the detailed answer much apprecieted!
have tried your setting.much better and yet i dont get a resault like yours also i get darker shadows.added a photo.sadly yellow still white.but,the tower now much better and so as the  paris sign but again not as good as yours.do you use cutum settings perhaps?
![better](https://github.com/natural-harmonia-gropius/hdr-toys/assets/80625946/4fafa68c-2182-46db-a275-e2e2226d95e6)

**Comment by ofirielon** [comment]
nvm,github compresion ruin it and it basicly looks now like yours.ty for the help.i cant wait for the color adjustments.

**Comment by natural-harmonia-gropius** [comment]
Today's update should alleviate this issue.
