### ISSUE TITLE
red understureated

### ISSUE THREAD

**Issue by ofirielon** [natural-harmonia-gropius/hdr-toys#45]
hello
red is very undersaturated in dynamic tone mapping to the point its some times translated to white specialy on highlights any way to fix it?

**Comment by natural-harmonia-gropius** [comment]
Please take some of clips using `ffmpeg -i input.mp4 -ss 00:00 -t 10 output.mp4`

---

Generally you can try:

Remove `glsl-shader=~~/shaders/hdr-toys/utils/chroma_correction.glsl`, or lower sigma and alpha in chroma_correction

Change `glsl-shader=~~/shaders/hdr-toys/gamut-mapping/jedypod.glsl` to `clip` or `bottosson`, or lower *_limit and boost *_threshold

**Comment by ofirielon** [comment]
thanks a lot.remove chroma correction,chane gamuet mapping to clip.now its perfect!
