### ISSUE TITLE
high gpu usage

### ISSUE THREAD

**Issue by ofirielon** [natural-harmonia-gropius/hdr-toys#46]
i noticed that after one of the last updates my gpu tams to 100% utilization.any fix or bypass?
using default code no changes at all beside sder peak to 100

**Comment by natural-harmonia-gropius** [comment]
I have noticed performance down in recent days too, even without hdr-toys. Sometimes fine, sometimes laggy with a picture. 

What I can say it that I haven't changed any things big, please report a new issue to mpv.

Maybe related to https://github.com/mpv-player/mpv/issues/12076
