### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by hooke007** [natural-harmonia-gropius/hdr-toys#47]
不定期打个标记吧，方便我做匹配的版本跟进

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/hdr-toys/releases/tag/v2308

**Comment by hooke007** [comment]
主要是上游api的变动和性能颠簸还是有点频繁，libplacebo的发版也不勤快，mpv这边编译也是跟进的git

有标记之后，这样就可以在某个节点附近找时间相近的mpv版本做稳定性兼容
