### ISSUE TITLE
2094-10 "tone-mapping-param" messing up brightness and saturation

### ISSUE THREAD

**Issue by geextahslex** [natural-harmonia-gropius/hdr-toys#49]
Hi, I have a problem with the "tone-mapping-param" with 2094-10. It is constantly shifting around and there is no value to fix it. It somehow resets for every new scene. If you are above (+)0 it effects some scenes and of you are under (-)0 then it effects the others. I just want to not be effected by this "feature".
And this should be possible, because when you use glsl tone mapping (which I don't have for 2094-10), then "tone-mapping-param" never effects the image.
 
There are conversations, where the one person is "normal" and when the camera goes to the other person in the dialog, then it messes with the brightness, which desaturates the picture.

The way it should look
![normal](https://github.com/natural-harmonia-gropius/hdr-toys/assets/139760266/4ee9667a-79e6-4a64-a650-20f508ae3125)

boosted brightness and desaturated picture
![shifted](https://github.com/natural-harmonia-gropius/hdr-toys/assets/139760266/f790e821-898c-4441-af2d-d962280a5abf)

**Comment by natural-harmonia-gropius** [comment]
report mpv's issue to mpv, tone-mapping-param or st2094-10 not my works.

**Comment by geextahslex** [comment]
solved: set "tone-mapping-param" to 0.400-0.500
