### ISSUE TITLE
what happend to lea.glsl?

### ISSUE THREAD

**Issue by geextahslex** [natural-harmonia-gropius/hdr-toys#50]
Hi,
I want to ask why did you remove lea? This is actually the one I'm using right now ^^
On the main page you also switched from lea to jedypod. Can I ask why?

**Comment by natural-harmonia-gropius** [comment]
I have re-checked lea's source code and toru's blog, they use CIE-Lab not Oklab and Jzazbz.
jedypod now have CIE-Lab's creative look, similar to them (orangish-red, purplish-blue).
Also, lea and toru are using 33 point lut, very imprecise.
No advantage, so just remove them.

**Comment by geextahslex** [comment]
Okay but for me there is also a difference in contrast between lea and the new jedypod. Im using the srgb.glsl "setup".
So lea gives a more "punchy" picture, which I kinda like. Maybe keep it, so others can also experiment a bit

**Comment by natural-harmonia-gropius** [comment]
> more "punchy" picture

Try to lower `shoulderAngle` or boost `toeStrength` on end of the dynamic.glsl, they accept values between [0, 1].

**Comment by geextahslex** [comment]
Is there a way to denoise low light/dark scenes? Blurr or make them more "stable"?

**Comment by natural-harmonia-gropius** [comment]
try nlmeans and hdeband

https://github.com/AN3223/dotfiles/tree/master/.config/mpv/shaders

**Comment by geextahslex** [comment]
I tried both, they are to heavy for my machine ^^

**Comment by natural-harmonia-gropius** [comment]
In general, film grain means high quality image. Enjoy with that. 😄
