### ISSUE TITLE
参考你的代码，在Android上实现了HDR转SDR

### ISSUE THREAD

**Issue by JonaNorman** [natural-harmonia-gropius/hdr-toys#53]
我在Android上也实现了[HDR转SDR](https://github.com/JonaNorman/HDRSample)功能，找不到你的联系方式只好提个issue表示感谢😏，我看你正在实现各种Tonemap，Android源码中也有自己的[tonemap](https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/libs/tonemap/tonemap.cpp)你可以参考，另外想了解有什么好的方式实现SDR转HDR

**Comment by natural-harmonia-gropius** [comment]
> 我在Android上也实现了[HDR转SDR](https://github.com/JonaNorman/HDRSample)功能

我有时间学一学WebGPU看看能不能浏览器上跑

> 找不到你的联系方式只好提个issue表示感谢

加群了

> Android源码中也有自己的[tonemap](https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/libs/tonemap/tonemap.cpp)你可以参考

有空再弄

> 另外想了解有什么好的方式实现SDR转HDR

设个亮度值拉伸信号，调整亮度滑块那样🤷‍♂️。反向映射应当只用在还原操作中，sdr中不同亮度的白色往往没有区别。不过像游戏引擎能获取原场景信息或者有某种AI能区分什么该亮什么该非常亮这样的可以反映射。
