### ISSUE TITLE
Errors on launch

### ISSUE THREAD

**Issue by boredness** [natural-harmonia-gropius/hdr-toys#54]
Seeing both of these errors on launch:

[hdr_toys_helper] 
[hdr_toys_helper] stack traceback:
[hdr_toys_helper] 	[C]: at 0x560587d00f30
[hdr_toys_helper] Lua error: /home/x/.config/mpv/scripts/hdr-toys-helper.lua:1: unexpected symbol near '{'

these show up when using and not using hdr-toys.

mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100

**Comment by natural-harmonia-gropius** [comment]
Sorry for that I cant do tests until this weekend. Let us check what is going wrong later🥱.

Error of helper.lua not quite a issue，80% of real HDR movies and tv （1000nit and 24fps）will be fine even without it.

**Comment by natural-harmonia-gropius** [comment]
> [hdr_toys_helper] Lua error: /home/x/.config/mpv/scripts/hdr-toys-helper.lua:1: unexpected symbol near '{'

Trace shows something wrong in first line, can you try re-download hdr-toys-helper.lua or upload your full hdr-toys-helper.lua?

**Comment by hooke007** [comment]
> (wget https://github.com/natural-harmonia-gropius/mpv-config/blob/master/portable_config/scripts/hdr-toys-helper.lua)

You were using wget command to download a page instead a file.
Here is the direct link to the actual file.
```
https://raw.githubusercontent.com/natural-harmonia-gropius/mpv-config/master/portable_config/scripts/hdr-toys-helper.lua
```
