### ISSUE TITLE
Image looks dark

### ISSUE THREAD

**Issue by f7el** [natural-harmonia-gropius/hdr-toys#60]
```
[ffmpeg/video] hevc: Failed setup for format vulkan: hwaccel initialisation returned error.
[ffmpeg] AVHWDeviceContext: Failed to find d3d11va adapter by vendor id 0x8086
[ffmpeg/video] hevc_cuvid: ctx->cvdl->cuvidCreateDecoder(&ctx->cudecoder, &cuinfo) failed -> CUDA_ERROR_NOT_SUPPORTED: operation not supported
[ffmpeg/video] hevc_cuvid: cuvid decode callback error
Error while decoding frame (hardware decoding)!
[ffmpeg/video] hevc_cuvid: cuvid decode callback error
Error while decoding frame (hardware decoding)!
[ffmpeg/video] hevc_cuvid: cuvid decode callback error
Error while decoding frame (hardware decoding)!
```

I'm seeing the above in the mpv console. looking at the logs, I noticed mpv falls back to software decoding. I dont think the image looks great but I havent been able to find the screenshots. I'm using mpv-config folder provided by dev. I can provide a log.

I'm playing an SDR video in HDR mode on Windows 10.

**Comment by natural-harmonia-gropius** [comment]
> I havent been able to find the screenshots

win + shift + s

> I'm playing an SDR video in HDR mode on Windows 10.

This designed for HDR to SDR, no things like inverse-tone-mapping or RTX Video HDR.

**Comment by f7el** [comment]
[mpv.conf.txt](https://github.com/natural-harmonia-gropius/hdr-toys/files/14298221/mpv.conf.txt)
I thought mpv screenshot would be better. I renamed the conf so it can be attached.

![image](https://github.com/natural-harmonia-gropius/hdr-toys/assets/10247894/f76c7cc2-2f63-42ba-a762-507580094f67)

**Comment by f7el** [comment]
![image](https://github.com/natural-harmonia-gropius/hdr-toys/assets/10247894/1579a31c-2984-4d39-9226-1c68951cee73)
[mpv.conf.txt](https://github.com/natural-harmonia-gropius/hdr-toys/files/14298259/mpv.conf.txt)

renamed conf so it can be attached.

**Comment by natural-harmonia-gropius** [comment]
You using default hdr-toys.conf? It won't do anything for SDR content.

https://support.microsoft.com/en-us/windows/hdr-settings-in-windows-2d767185-38ec-7fdc-6f97-bbc6c5ef24e6
"Some desktop apps appear too dark on an HDR display." most probably what you need.
