### ISSUE TITLE
Clippings on ToneMapping

### ISSUE THREAD

**Issue by danbezerra** [natural-harmonia-gropius/hdr-toys#70]
Just like "vanilla" MPV/Libplacebo, I see clippings mainly on Blue and Green patterns. This is using your latest files and a clean MPV config with only two lines: vo=gpu-next and the include to load the hdr-toys.config.

Same display with MadVR shows almost no clipping - with the exception of a bit of red.

(PowerToys)
![image](https://github.com/user-attachments/assets/fcd5dff8-086a-406d-b42a-54cc944c59cd)

(MadVR)
![image](https://github.com/user-attachments/assets/9781715c-309f-4866-9c7c-891c2fef0ef8)

Do you know what may be causing this clipping? As I said, the same happens with my main MPV config, using libplacebo, Spline, Tonemapping to SDR BT.709.

**Comment by natural-harmonia-gropius** [comment]
Use `st2094-10`(hdr-toys' one) for this kind of samples.

**Comment by danbezerra** [comment]
Thanks, I can confirm that with st2094-10 I don't see the same clippings. But why not use it for regular movies as well, since it won't clip as the default one? Are you saying that those samples are not representative of real scenarios? Wouldn't a movie have the same risk of clipping as well? Or is a trade off?

Sorry for all the questions, just want to understand the background.

**Comment by danbezerra** [comment]
Thanks. I will try both dynamic and st2094-10 with real movie samples and see which one I like the most. Two other questions:

1. set glsl-shader-opts L_sdr=100 returns an error (unexpected extra parameters). I managed to get it fixed by just adding glsl-shader-opts L_sdr=100 (no "set") in the config. Not sure if the instructions are old or if I'm making a mistake on my side.

2. If I want my gamut to stay at BT.2020, do I still need to use Clip and have define from  BT2020. define to BT2020? Or OK to just not load the the gamut-mapping shader? 

3. Inside Clip.glsl, I saw a place to define custom chromaticity. If I know my custom red,green,blue x and y (from HCFR calibration results), is there a way to define them there?

**Comment by natural-harmonia-gropius** [comment]
> 1

That is syntax of console/input.conf like `set pause yes`. BTW the documentation is not clear enough.

> 2

Remove gamut-mapping line when input matches output.

> 3

`#define to      Chromaticity(vec2(0.64, 0.33), BT709.g, BT709.b, D65)`

Use vec2(x, y) or exist point in below. x and y positions are value of CIE-xy.

I didn't used HCFR, but I saw xyY in screenshots, that should be what you need. If the values ​​are not between 0 and 1, divide by 100.
