### ISSUE TITLE
hlg doesn't work with mpv's tone-mapping hdr-compute-peak

### ISSUE THREAD

**Issue by geextahslex** [natural-harmonia-gropius/hdr-toys#75]
Hi, I use mpv's tone-mapping with `hdr-compute-peak` with `pq` and it works normally, but this doesn't work with `hlg`. 
Am I doing something wrong? Can this be fixed?

Thank you :)

```
tone-mapping=st2094-10
hdr-compute-peak=yes
allow-delayed-peak-detect
target-prim=bt.2020
target-trc=hlg

glsl-shader=~~/shaders/hdr-toys/transfer-function/hlg_inv.glsl
glsl-shader=~~/shaders/hdr-toys/utils/black_point_compensation.glsl
glsl-shader=~~/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/bt1886.glsl
```

![compute peak](https://github.com/user-attachments/assets/295b7e56-69a5-4ba9-914b-9002c014b730)

**Comment by natural-harmonia-gropius** [comment]
What is "doesn't work"? If you meaning 100->100, ask to mpv/libplacebo.

**Comment by geextahslex** [comment]
Doesn't work means it is just 1 to 1, there is no compute
I already asked. https://github.com/mpv-player/mpv/discussions/15505
